[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"
