[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
# healthcheckPath = "/health"
# healthcheckTimeout = 900
# healthcheckInterval = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2

[env]
NODE_ENV = "production"
PORT = "3000"
